export const listStyles = {
  ul: [
    { value: 'disc', label: 'Dolu daire', markers: ['•', '•', '•'] },
    { value: 'circle', label: 'Boş daire', markers: ['○', '○', '○'] },
    { value: 'square', label: 'Kare', markers: ['▪', '▪', '▪'] },
  ],
  ol: [
    { value: 'decimal', label: 'Sayılar', markers: ['1.', '2.', '3.'] },
    { value: 'lower-alpha', label: 'Küçük harfler', markers: ['a.', 'b.', 'c.'] },
    { value: 'upper-alpha', label: 'Büyük harfler', markers: ['A.', 'B.', 'C.'] },
    { value: 'lower-roman', label: 'Küçük Roma rakamları', markers: ['i.', 'ii.', 'iii.'] },
    { value: 'upper-roman', label: 'Büyük Roma rakamları', markers: ['I.', 'II.', 'III.'] },
    { value: 'decimal-leading-zero', label: 'Başında sıfır', markers: ['01.', '02.', '03.'] },
  ],
}
export const lineHeights = ['', '1', '1.15', '1.5', '1.65', '2', '2.5', '3']
export const symbolGroups = {
  Simgeler: [
    '©',
    '®',
    '™',
    '§',
    '¶',
    '†',
    '‡',
    '•',
    '…',
    '–',
    '—',
    '«',
    '»',
    '“',
    '”',
    '‘',
    '’',
    '°',
    '‰',
    '✓',
    '✗',
    '★',
    '☆',
    '♥',
  ],
  Matematik: [
    '±',
    '×',
    '÷',
    '≠',
    '≈',
    '≤',
    '≥',
    '∞',
    '√',
    '∑',
    '∏',
    '∫',
    '∂',
    '∆',
    'π',
    'α',
    'β',
    'γ',
    'θ',
    'λ',
    'μ',
    'Ω',
    '→',
    '⇌',
  ],
  'Para birimleri': ['$', '€', '£', '¥', '₺', '₹', '₩', '₽', '¢', '₿'],
  Emoji: [
    '😀',
    '😊',
    '🙂',
    '🤔',
    '😎',
    '🎉',
    '🚀',
    '💡',
    '🎯',
    '✅',
    '📌',
    '📚',
    '💻',
    '🌍',
    '🌱',
    '❤️',
    '👍',
    '👏',
    '🔥',
    '⭐',
    '🧪',
    '🔬',
    '⚠️',
    '📝',
  ],
}
