import { test, expect } from '@playwright/test'
const body = (page) => page.frameLocator('.studio-editor-frame').locator('body')
async function setup(page, html = '<p><br></p>') {
  await page.goto('/')
  await expect(body(page)).toBeVisible()
  await page.getByRole('button', { name: 'Kaynak kodu', exact: true }).click()
  await page.getByRole('textbox', { name: 'HTML kaynak kodu' }).fill(html)
  await page.getByRole('button', { name: 'Değişiklikleri uygula' }).click()
  await expect(page.locator('dialog')).toHaveCount(0)
  await body(page).locator('p,pre').last().click()
  await body(page).press('End')
}
test('slash search, keyboard selection, escape and undo', async ({ page }) => {
  await setup(page)
  await page.keyboard.type('/h2')
  await expect(page.getByRole('menu', { name: 'Blok ekle' })).toBeVisible()
  await page.keyboard.press('Enter')
  await expect(body(page).locator('h2')).toHaveCount(1)
  await page.getByRole('button', { name: 'Geri al', exact: true }).click()
  await expect(body(page)).toContainText('/h2')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('menu', { name: 'Blok ekle' })).toHaveCount(0)
})
test('markdown turns prefixes into blocks as a single undoable change', async ({ page }) => {
  await setup(page, '<p>##</p>')
  await page.keyboard.press('Space')
  await expect(body(page).locator('h2')).toHaveCount(1)
  await page.getByRole('button', { name: 'Geri al', exact: true }).click()
  await expect(body(page).locator('p')).toHaveText('##')
  await setup(page, '<p>1.</p>')
  await page.keyboard.press('Space')
  await expect(body(page).locator('ol li')).toHaveCount(1)
  await setup(page, '<pre>##</pre>')
  await page.keyboard.press('Space')
  await expect(body(page).locator('h2')).toHaveCount(0)
  await expect(body(page).locator('pre')).toContainText('##')
})
test('typed and pasted HTTP links are automatic, plain paste and code remain text', async ({
  page,
}) => {
  await setup(page, '<p>https://example.com/page</p>')
  await page.keyboard.press('Space')
  await expect(body(page).locator('a')).toHaveAttribute('href', 'https://example.com/page')
  await page.getByRole('button', { name: 'Geri al', exact: true }).click()
  await expect(body(page).locator('a')).toHaveCount(0)
  await setup(page)
  await body(page).evaluate((root) => {
    const data = new DataTransfer()
    data.setData('text/plain', 'https://example.com')
    const e = new Event('paste', { bubbles: true, cancelable: true })
    Object.defineProperty(e, 'clipboardData', { value: data })
    root.dispatchEvent(e)
  })
  await expect(body(page).locator('a')).toHaveAttribute('href', 'https://example.com/')
  await setup(page, '<pre><br></pre>')
  await page.keyboard.type('https://example.com ')
  await expect(body(page).locator('a')).toHaveCount(0)
})

test('block controls reorder with keyboard and pointer, keep content and undo in one step', async ({
  page,
}) => {
  await setup(page, '<p>Birinci</p><p>İkinci</p><p>Üçüncü</p>')
  await page.getByRole('button', { name: 'Bloğu yukarı taşı', exact: true }).click()
  await expect(body(page).locator('p')).toHaveText(['Birinci', 'Üçüncü', 'İkinci'])
  await page.getByRole('button', { name: 'Geri al', exact: true }).click()
  await expect(body(page).locator('p')).toHaveText(['Birinci', 'İkinci', 'Üçüncü'])
  await body(page).locator('p').first().click()
  const grip = page.getByRole('button', { name: 'Bloğu sürükle; ok tuşlarıyla taşı', exact: true })
  await expect(grip).toBeVisible()
  const from = await grip.boundingBox(),
    to = await body(page).locator('p').last().boundingBox()
  await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2)
  await page.mouse.down()
  await page.mouse.move(to.x + to.width / 2, to.y + to.height + 6, { steps: 8 })
  await expect(page.locator('.studio-block-drop')).toBeVisible()
  await page.mouse.up()
  await expect(body(page).locator('p')).toHaveText(['İkinci', 'Üçüncü', 'Birinci'])
  await page.getByRole('button', { name: 'Geri al', exact: true }).click()
  await expect(body(page).locator('p')).toHaveText(['Birinci', 'İkinci', 'Üçüncü'])
  await body(page).locator('p').first().click()
  await grip.focus()
  await grip.press('ArrowDown')
  await expect(body(page).locator('p')).toHaveText(['İkinci', 'Birinci', 'Üçüncü'])
  await body(page).locator('p').first().click()
  const cancelFrom = await grip.boundingBox(),
    cancelTo = await body(page).locator('p').last().boundingBox()
  await page.mouse.move(cancelFrom.x + cancelFrom.width / 2, cancelFrom.y + cancelFrom.height / 2)
  await page.mouse.down()
  await page.mouse.move(cancelTo.x + 40, cancelTo.y + cancelTo.height + 5, { steps: 5 })
  await expect(page.locator('.studio-block-drop')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('.studio-block-drop')).toHaveCount(0)
  await page.mouse.up()
  await expect(body(page).locator('p')).toHaveText(['İkinci', 'Birinci', 'Üçüncü'])
})
