import { test, expect } from '@playwright/test'
const body = (page) => page.frameLocator('.studio-editor-frame').first().locator('body')

test('calculated cells and conditional fields expose portable model data', async ({ page }) => {
  await page.goto('/')
  await expect(body(page)).toHaveText('Birinci belge')
  const editor = page.locator('.studio-editor-embed').first()
  await body(page).locator('p').click()
  await page.keyboard.press('End')
  await editor.getByRole('button', { name: 'Tablo ekle', exact: true }).click()
  await page.getByRole('button', { name: '2 sütun, 2 satır', exact: true }).click()
  await body(page).locator('td').first().click()
  await editor
    .locator('.native-menubar')
    .getByRole('button', { name: 'Tablo', exact: true })
    .click()
  await page.getByRole('menuitem', { name: 'Tablo formülü', exact: true }).click()
  await page.getByRole('textbox', { name: 'Formül', exact: true }).fill('=SUM(10,20)')
  await page.getByRole('button', { name: 'Formülü uygula', exact: true }).click()
  await expect(body(page).locator('[data-studio-formula]')).toHaveText('30')
  await body(page).focus()
  await page.keyboard.press('Control+End')
  await editor.locator('.native-menubar').getByRole('button', { name: 'Ekle', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Koşullu alan', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Ekle', exact: true }).click()
  await page.getByRole('button', { name: 'Şemalı belgeyi oku', exact: true }).click()
  const json = await page.locator('#schema-model').textContent()
  expect(json).toContain('data-studio-formula')
  expect(json).toContain('data-studio-condition')
  expect(json).not.toContain('contenteditable')
  await expect(page.locator('#model-error')).toBeEmpty()
})
test('schema operations integrate with HTML, identity, undo and stale revisions', async ({
  page,
}) => {
  await page.goto('/')
  await expect(body(page)).toHaveText('Birinci belge')
  await page.getByRole('button', { name: 'Şemalı belgeyi oku' }).click()
  const before = JSON.parse(await page.locator('#schema-model').textContent())
  expect(before.schemaVersion).toBe(2)
  await page.getByRole('button', { name: 'Şemalı işlem uygula' }).click()
  await expect(body(page)).toHaveText('Şemalı belge')
  await page.getByRole('button', { name: 'Şemalı işlem uygula' }).click()
  await expect(page.locator('#model-error')).toContainText('Belge değişti')
  await expect(body(page)).toHaveText('Şemalı belge')
  await page.getByRole('button', { name: 'API geri al' }).click()
  await expect(body(page)).toHaveText('Birinci belge')
  await page.getByRole('button', { name: 'Şemalı belgeyi oku' }).click()
  const after = JSON.parse(await page.locator('#schema-model').textContent())
  expect(after.blocks[0].id).toBe(before.blocks[0].id)
})

test('footnotes and merge fields expose portable schema data without editing attributes', async ({
  page,
}) => {
  await page.goto('/')
  await expect(body(page)).toHaveText('Birinci belge')
  const editor = page.locator('.studio-editor-embed').first()
  await body(page).locator('p').selectText()
  await editor.getByRole('button', { name: 'Dipnotlar', exact: true }).click()
  await page.getByRole('textbox', { name: 'Dipnot metni' }).fill('Package footnote')
  await page.getByRole('dialog').getByRole('button', { name: 'Ekle', exact: true }).click()
  await editor.getByRole('button', { name: 'Şablon değişkenleri', exact: true }).click()
  await page.getByRole('textbox', { name: 'Değişken adı' }).fill('Customer.Name')
  await page.getByRole('dialog').getByRole('button', { name: 'Ekle', exact: true }).click()
  await page.getByRole('button', { name: 'Şemalı belgeyi oku' }).click()
  const json = await page.locator('#schema-model').textContent()
  expect(JSON.parse(json).schemaVersion).toBe(2)
  expect(json).toContain('data-studio-footnote-ref')
  expect(json).toContain('data-studio-field')
  expect(json).not.toContain('contenteditable')
  await expect(page.locator('#model-error')).toBeEmpty()
  await expect(page.frameLocator('.studio-editor-frame').nth(1).locator('body')).toHaveText(
    'İkinci belge',
  )
})
